name: 'Build and Deploy R to Cloud Run'

on:
  workflow_dispatch:
  push:
    branches:
      - '"main"'

env:
  PROJECT_ID: symp-r 
  GAR_LOCATION: us-central1
  GAR_NAME: gh-demo
  REGION: us-central1 
  SERVICE: plumber-api
  
jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: google auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{secrets.GCP_CREDENTIALS}}'

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="$${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"
      
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17' 
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
         

          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}'


