name: Build and Deploy Plumber API to Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Set environment variables
  PROJECT_ID: r-lang-440905
  REGION: us-central1
  SERVICE_NAME: plumber-api
  IMAGE_TAG: latest
  GAR_LOCATION: us-central1-docker.pkg.dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up R environment manually
    - name: Install R and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          r-base \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          docker.io

    # Install the 'plumber' package in R
    - name: Install plumber package
      run: |
        R -e "install.packages('plumber')"

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t "${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}
